-- SYSDIANE413DEV.TMPSEJOUR definition

CREATE TABLE "SYSDIANE413DEV"."TMPSEJOUR" 
   (	"IDSEJOUREXTERN" VARCHAR2(255), 
	"IDSEJOURINTERN" NUMBER(*,0), 
	"IDPATIENTEXTERN" VARCHAR2(255), 
	"DATEIN" DATE, 
	"DATEOUT" DATE, 
	"DATEMAJ" DATE, 
	"MAJ" NUMBER(*,0), 
	"TYPESEJOUR" NUMBER(*,0), 
	"CHAMBRE" VARCHAR2(255), 
	"LIT" VARCHAR2(255), 
	"IDTMPSEJOUR" NUMBER(*,0), 
	"UF_MEDICALE" VARCHAR2(255), 
	"UF_HEBERGEMENT" VARCHAR2(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 9437184 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIANE_T" ;
  CREATE UNIQUE INDEX "SYSDIANE413DEV"."PK_TMPSEJOUR" ON "SYSDIANE413DEV"."TMPSEJOUR" ("IDTMPSEJOUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIANE_T" ;
ALTER TABLE "SYSDIANE413DEV"."TMPSEJOUR" ADD CONSTRAINT "PK_TMPSEJOUR" PRIMARY KEY ("IDTMPSEJOUR")
  USING INDEX "SYSDIANE413DEV"."PK_TMPSEJOUR"  ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER "SYSDIANE413DEV"."TG_PK_TMPSEJOUR" BEFORE INSERT ON TMPSEJOUR FOR EACH ROW BEGIN SELECT sq_TMPSEJOUR.NextVal into :New.IDTMPSEJOUR FROM DUAL; END;


/
ALTER TRIGGER "SYSDIANE413DEV"."TG_PK_TMPSEJOUR" ENABLE;

CREATE INDEX "SYSDIANE413DEV"."INDEX_TMPSEJOUR2" ON "SYSDIANE413DEV"."TMPSEJOUR" ("IDSEJOUREXTERN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIANE_T" ;
  CREATE INDEX "SYSDIANE413DEV"."INDEX_TMPSEJOUR3" ON "SYSDIANE413DEV"."TMPSEJOUR" ("IDPATIENTEXTERN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIANE_T" ;
  CREATE UNIQUE INDEX "SYSDIANE413DEV"."PK_TMPSEJOUR" ON "SYSDIANE413DEV"."TMPSEJOUR" ("IDTMPSEJOUR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 2097152 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIANE_T" ;
  CREATE INDEX "SYSDIANE413DEV"."INDEX_TMPSEJOUR" ON "SYSDIANE413DEV"."TMPSEJOUR" ("IDPATIENTEXTERN", "IDSEJOUREXTERN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 5242880 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIANE_T" ;