-- SYSDIANE413DEV.TMPMOUVEMENT definition

CREATE TABLE "SYSDIANE413DEV"."TMPMOUVEMENT" 
   (	"ID" NUMBER(*,0), 
	"SEJOURID" NUMBER(10,0) NOT NULL ENABLE, 
	"IDMVTEXTERN" VARCHAR2(255) NOT NULL ENABLE, 
	"TYPIN" NUMBER(10,0), 
	"TYPOUT" NUMBER(10,0), 
	"DATEIN" DATE NOT NULL ENABLE, 
	"DATEOUT" DATE, 
	"UFMED" VARCHAR2(255), 
	"UFHEB" VARCHAR2(255), 
	"ROOM" VARCHAR2(255), 
	"BED" VARCHAR2(255), 
	"DELETED" NUMBER(1,0), 
	"DATEMAJ" DATE, 
	"VISIBLE" NUMBER(1,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_TMPMOUVEMENT" PRIMARY KEY ("ID");

--   USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
--   BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--   TABLESPACE "DIANE_T"  ENABLE
--    ) SEGMENT CREATION IMMEDIATE 
--   PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
--  NOCOMPRESS LOGGING
--   STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--   PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
--   BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--   TABLESPACE "DIANE_T" ;

CREATE OR REPLACE EDITIONABLE TRIGGER "SYSDIANE413DEV"."TG_PK_TMPMOUVEMENT" BEFORE INSERT ON TMPMOUVEMENT FOR EACH ROW BEGIN SELECT sq_TMPMOUVEMENT.NextVal into :New.ID FROM DUAL; END;





/
ALTER TRIGGER "SYSDIANE413DEV"."TG_PK_TMPMOUVEMENT" ENABLE;

CREATE INDEX "SYSDIANE413DEV"."IDX_FK_100" ON "SYSDIANE413DEV"."TMPMOUVEMENT" ("SEJOURID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIANE_T" ;
  CREATE UNIQUE INDEX "SYSDIANE413DEV"."PK_TMPMOUVEMENT" ON "SYSDIANE413DEV"."TMPMOUVEMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIANE_T" ;


-- SYSDIANE413DEV.TMPMOUVEMENT foreign keys

ALTER TABLE "SYSDIANE413DEV"."TMPMOUVEMENT" ADD CONSTRAINT "FK_REF_100" FOREIGN KEY ("SEJOURID")
	  REFERENCES "SYSDIANE413DEV"."TMPSEJOUR" ("IDTMPSEJOUR") ENABLE;