-- SYSDIANE413DEV.TMPDONNEEPATIENT definition

CREATE TABLE "SYSDIANE413DEV"."TMPDONNEEPATIENT" 
   (  "IDTMPDONNEEPATIENT" NUMBER(*,0), 
  "IPP" VARCHAR2(255), 
  "NOMPATRONYMIQUE" VARCHAR2(255), 
  "NOMMARITAL" VARCHAR2(255), 
  "PRENOM" VARCHAR2(255), 
  "SEXE" VARCHAR2(255), 
  "DATENAISS" DATE, 
  "IDDONNEE" NUMBER(*,0), 
  "IDACTIVEX" NUMBER(*,0), 
  "DONNEE" VARCHAR2(2048), 
  "IDEXTERN" VARCHAR2(255), 
  "MAJ" NUMBER(*,0), 
  "DATEMAJ" DATE DEFAULT TO_DATE('30/12/1899 00:00:00', 'dd/mm/yyyy HH24:MI:SS') NOT NULL ENABLE, 
  "IDDONNEEEXTERNE" VARCHAR2(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIANE_T" ;
  CREATE UNIQUE INDEX "SYSDIANE413DEV"."PK_TMPDONNEEPATIENT" ON "SYSDIANE413DEV"."TMPDONNEEPATIENT" ("IDTMPDONNEEPATIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIANE_T" ;
ALTER TABLE "SYSDIANE413DEV"."TMPDONNEEPATIENT" ADD CONSTRAINT "PK_TMPDONNEEPATIENT" PRIMARY KEY ("IDTMPDONNEEPATIENT")
  USING INDEX "SYSDIANE413DEV"."PK_TMPDONNEEPATIENT"  ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER "SYSDIANE413DEV"."TG_PK_TMPDONNEEPATIENT" BEFORE INSERT ON TMPDONNEEPATIENT FOR EACH ROW BEGIN SELECT sq_TMPDONNEEPATIENT.NextVal into :New.IDTMPDONNEEPATIENT FROM DUAL; END;







/
ALTER TRIGGER "SYSDIANE413DEV"."TG_PK_TMPDONNEEPATIENT" ENABLE;

CREATE UNIQUE INDEX "SYSDIANE413DEV"."PK_TMPDONNEEPATIENT" ON "SYSDIANE413DEV"."TMPDONNEEPATIENT" ("IDTMPDONNEEPATIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DIANE_T" ;